### ISSUE TITLE
[05-14-2018] nightly build for ONAP SO head failed upstream "Build status: failure"

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#48]
Issue: nightly build for ONAP SO head failed upstream

What I see now:
- Error logs on https://gitlab.cncf.ci/onap/so/-/jobs/87213 show

```
Build status: failure

$ /onapciservice/bin/build_pipeline download_container --integration=$INTEGRATION_NAME --release-type=$INTEGRATION_RELEASE_TYPE so
/onapciservice/lib/crosscloudci/ciservice/onap/build_pipeline.rb:70:in `head_container_image_tag': undefined method `split' for nil:NilClass (NoMethodError)
	from /onapciservice/lib/crosscloudci/ciservice/onap/build_pipeline.rb:19:in `container_image_tag'
	from /onapciservice/lib/crosscloudci/ciservice/build_pipeline.rb:121:in `container_artifact_url'
	from /onapciservice/lib/crosscloudci/ciservice/build_pipeline.rb:109:in `download_container'
	from /onapciservice/bin/build_pipeline:83:in `download_container'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /onapciservice/bin/build_pipeline:195:in `<main>'
ERROR: Job failed: exit code 1
```

What I would like to see: 
- Stop integration process when Jenkins build status is `failure`

**Comment by lixuna** [comment]
https://jenkins.onap.org/view/Daily-Jobs/job/so-master-docker-version-java-daily/394/ finished with "success" 

The scheduled job on Wed, May 16th will use the passing build and cncf.ci should be green for ONAP head.
