### ISSUE TITLE
[06-18-2018] ONAP Head release fails build stage on cncf.ci

### ISSUE THREAD

**Issue by lixuna** [crosscloudci/crosscloudci#57]
Date: Monday, June 18, 2018

Issue: ONAP Head release fails build stage on cncf.ci

Job: https://gitlab.cncf.ci/onap/so/-/jobs/99018

Error:

```
$ cd -
/builds/onap/so
$ /onapciservice/bin/build_pipeline build_status --integration=$INTEGRATION_NAME --release-type=$INTEGRATION_RELEASE_TYPE so
Build status: failure
$ /onapciservice/bin/build_pipeline download_container --integration=$INTEGRATION_NAME --release-type=$INTEGRATION_RELEASE_TYPE so
/onapciservice/lib/crosscloudci/ciservice/onap/build_pipeline.rb:70:in `head_container_image_tag': undefined method `split' for nil:NilClass (NoMethodError)
	from /onapciservice/lib/crosscloudci/ciservice/onap/build_pipeline.rb:19:in `container_image_tag'
	from /onapciservice/lib/crosscloudci/ciservice/build_pipeline.rb:121:in `container_artifact_url'
	from /onapciservice/lib/crosscloudci/ciservice/build_pipeline.rb:109:in `download_container'
	from /onapciservice/bin/build_pipeline:83:in `download_container'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /usr/local/bundle/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /onapciservice/bin/build_pipeline:195:in `<main>'
ERROR: Job failed: exit code 1
```

**Comment by lixuna** [comment]
The last passing build was on June 15th. See https://jenkins.onap.org/view/so/job/so-master-docker-version-java-daily/ for history.
